apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: weasel-frontend-hpa
  namespace: weasel-frontend
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: weasel-frontend
  minReplicas: 1
  maxReplicas: 1
  metrics:
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80  # 메모리 사용률을 60%로 설정
  # - type: Resource
  #   resource:
  #     name: cpu
  #     target:
  #       type: Utilization
  #       averageUtilization: 80  # CPU 사용률을 80%로 설정
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 60
      selectPolicy: Max
      policies:
      - type: Pods
        value: 2
        periodSeconds: 15
      # - type: Percent
      #   value: 50
      #   periodSeconds: 15
    scaleDown:
      stabilizationWindowSeconds: 60
      selectPolicy: Min
      policies:
      - type: Pods
        value: 2
        periodSeconds: 15
      # - type: Percent
      #   value: 50
      #   periodSeconds: 15
